"""empty message

Revision ID: 51b59bace9fd
Revises: f6be72f1e1d1
Create Date: 2024-09-22 17:13:21.057488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b59bace9fd'
down_revision = 'f6be72f1e1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
